### ISSUE TITLE
[Device Support Request] Tuya TS0601 by _TZE200_nklqjk62 - Zigbee Garage Door Opener

### ISSUE THREAD

**Issue by cchobanIL** [zigpy/zha-device-handlers#1793] opened 2022-09-28 16:06 UTC
This device is picked up immediately through ZHA, but comes through with only two entities; LQI and RSSI.  And has no controllable state or switches associated with it.

There is a sensor with wire that runs from this device to the wall near the garage door, with the other side (not on the wire) simply stuck on the door.  It's really like any other door sensor, but one side is powered via wire, by the main device.

To be useful, ZHA needs to pick up the fact that there is a sensor, and then there needs to be a state (open/closed) associated with it, just like a normal door sensor.  Then, ZHA would also need to recognize and control the electronic switch within the device.  I don't know the name of the type of switch, but it literally is just like a button press that sends a signal.  Just like a normal garage door button on a wall, the electronic switch in this device would act like, activate once, door goes up, activate another time, door goes down.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE200_nklqjk62",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
There is no diagnostic information available.
```

</details>

<details>
<summary>Additional logs</summary>

```
None
![Screenshot](https://user-images.githubusercontent.com/92334235/192830138-f45725e6-91ca-4e20-a046-06ce6227b80b.png)

```

</details>

**Additional context**

**Comment by javicalle** [comment] 2022-09-28 22:18
Duplicate of https://github.com/zigpy/zha-device-handlers/issues/1260

Thanks for the detailed description, but the device has been already reported.

**Comment by cchobanIL** [comment] 2022-09-29 17:09
Thank you for by he response! Just a question of process… if the device has already been reported, does that mean it’s on a list and may get worked? Or does it mean it’s been looked at and nothing can be done?

Many thanks!

**Comment by MattWestb** [comment] 2022-09-29 17:40
I the comment https://github.com/zigpy/zha-device-handlers/issues/1260#issuecomment-1170017766 the user is writing all is working OK.
Hi is having the same devices as you (MODELS_INFO) so if you reading the thread and doing the same config of local quirk and adding the code posted your device shall working if all is being OK.

Sadly no one have making one PR for adding it in ZHA so must using local quirk for getting it working.

**Comment by javicalle** [comment] 2022-09-29 17:43
Mainly it is marked as duplicate so as not to disperse the information and so that everyone reads and contributes the information in a single place.

In this particular case, work has been done on the device to integrate it into HA and for some users it appears to be working (at least 'partially').
Normally, in order to integrate all the functionalities, it is necessary for someone with the device to test and (if they cannot implement the solution) provide the evidence so that the functionalities can be implemented.

A functional version was not reached for this device for various reasons.
On the one hand, the entity to manage the motor is not the most appropriate (a switch when the best would be a button). This depends more on HA than on the quirk.
On the other hand, there has been no more feedback from users, so the tasks are falling to the bottom of the priorities... it's not pretty, but it's reality.

If you want to continue trying a working version, you can try the version from [the other post](https://github.com/zigpy/zha-device-handlers/issues/1260#issuecomment-1168792380) and continue the conversation there.

PS: Hi @MattWestb 😄

**Comment by TheJulianJES** [comment] 2023-01-04 04:53
Closing in favor of https://github.com/zigpy/zha-device-handlers/issues/1260

**Closed by TheJulianJES** 2023-01-04 04:53 UTC
Labels: Tuya
