### ISSUE TITLE
[BUG] TS0201 Reporting Humidity off by factor of 10

### ISSUE THREAD

**Issue by romain1206** [zigpy/zha-device-handlers#1684] opened 2022-08-07 16:57 UTC
hello,

Connected a Tuya TS0201 and watch reporting. 
Temperature is correct, Humidity displays 47.3% (on screen) but reports 4.73 via ZHA

**Comment by javicalle** [comment] 2022-08-07 20:30
Please, fill the new bug template with the relevant info. At least, the device's signature and a vendor URL to identify the device.

Thanks in advance.

**Comment by javicalle** [comment] 2022-08-07 21:43
Maybe duplicate of #1667

**Comment by dmulcahey** [comment] 2022-08-30 11:24
Please do as instructed by @javicalle

**Closed by dmulcahey** 2022-08-30 11:24 UTC
