### ISSUE TITLE
aqara Fp1 regions support

### ISSUE THREAD

**Issue by alexisiglesias1** [zigpy/zha-device-handlers#2228] opened 2023-02-26 13:37 UTC
**Is your feature request related to a problem? Please describe.**

Region support in the Aqara FP1 sensor would be great, there are folks who have issues with ceiling fans, and other areas of a monitored room that require ignoring for the sensor to function properly, this feature is already supported on Z2M

**Describe the solution you'd like**

Aqara FP1 device itself supports regions, I'd like to be able to define regions, and have region information in the detection event so that I can filter in / out events that I care about.

</details>

**Additional context**

**Comment by TheJulianJES** [comment] 2023-02-26 21:28
Duplicate of: https://github.com/zigpy/zha-device-handlers/issues/2202

**Closed by TheJulianJES** 2023-02-26 21:28 UTC
Labels: duplicate
