### ISSUE TITLE
[Device Support Request]  Bosch Radiator Thermostat 2

### ISSUE THREAD

**Issue by Asky82** [zigpy/zha-device-handlers#3300] opened 2024-08-13 13:00 UTC
### Problem description

Hi All, 

I hope that someone can help me :) 

I would like to add to my HA OS the  Bosch Radiator Thermostat 2 via a Conbee V3.

I'm trying to add the Thermostat via ZHA.permit and inserting the  IEEE Source and Installation code. I tried also with the QR code but I got always the following error: 

"Translation Error: The intl string context variable "services" was not provided to the string "Impossibile eseguire l'azione: {services}" Unknown error"

<img width="1098" alt="2024-08-13 14_51_41-Strumenti per sviluppatori – Home Assistant" src="https://github.com/user-attachments/assets/74f32dd0-19e0-433e-87f5-5e86f388e41c">

![IMG_3608](https://github.com/user-attachments/assets/893a38dd-084d-42bc-bd3d-07558c0fdc4c)

Any idea on what I could try?  Thank you so much!!!

### Solution description

No solution so far.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
zigpy_deconz.exception.CommandError: <CommandId.write_parameter: 11>, status: <Status.UNSUPPORTED: 4>
2024-08-13 11:28:50.147 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139963417132720] Error handling message: Unknown error (unknown_error) Gigi from 192.168.178.82 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1799, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1102, in _async_admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/zha/websocket_api.py", line 1287, in permit
    await application_controller.permit_with_link_key(
  File "/usr/local/lib/python3.12/site-packages/zigpy_deconz/zigbee/application.py", line 116, in permit_with_link_key
    await self._api.write_parameter(
  File "/usr/local/lib/python3.12/site-packages/zigpy_deconz/api.py", line 849, in write_parameter
    await self.send_command(
  File "/usr/local/lib/python3.12/site-packages/zigpy_deconz/api.py", line 508, in send_command
    return await self._command(cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy_deconz/api.py", line 589, in _command
    return await fut
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by Hedda** [comment] 2024-08-14 12:29
FYI, if it is "BOSCH Radiator Thermostat II" (Model: BTH-RA) then this is a duplicate of this existing open issues being tracked:

* https://github.com/zigpy/zha-device-handlers/issues/2476

Also see this related discussion thread in the Home Assistant community forum:

* https://community.home-assistant.io/t/bosch-thermostat-2/492845/

Notes: To pair this device you have to install the device via its installation code. The installation code can be obtained by scanning the QR-code on the inside of the battery cover with your smartphone. Then get the device into pairing mode. Paste the code you got from the QR-code ...

https://www.home-assistant.io/integrations/zha#action-zhapermit

PS; Also note that support for commissioning Zigbee 3.0 devices via “Install Code” or “QR Code” via the zha.permit action has so far only been implemented for ‘ezsp’ (Silicon Labs EmberZNet) or ‘znp’ (Texas Instruments) radio type in ZHA. Other radio types are missing support in their respective [radio libraries for zigpy](https://github.com/zigpy/) or manufacturer’s firmware commands/APIs. That is you need a Zigbee Coordinator that uses a Silabs or TI chip. See ZHA limitations:

https://www.home-assistant.io/integrations/zha#limitations

and 

https://www.home-assistant.io/integrations/zha#recommended-zigbee-radio-adapters-and-modules

**Comment by Asky82** [comment] 2024-08-14 13:50
Thanks, yes is then a duplicate. Would be better that I ask support there then?

Quick questions regarding the Zigbee limitation and ZHA Permit.  Since I saw that my ConBee3 doesn't have Silicon Labs EmberZNet or Texas means that I cannot pair devices via zha.permit?

Thanks

**Comment by Hedda** [comment] 2024-08-14 20:22
> Thanks, yes is then a duplicate. Would be better that I ask support there then?

Yes please do, (you should close this #3300  if it is a duplicate of #2476 and post/continue in that existing #2476 issue instead).

> Quick questions regarding the Zigbee limitation and ZHA Permit. Since I saw that my ConBee3 doesn't have Silicon Labs EmberZNet or Texas means that I cannot pair devices via zha.permit?

That is correct, (there is no good reason to buy a ConBee 3 if you use ZHA as it has this limitation and not maintained for as much as missing expansive doucmentation and lack developers activly interested in it for zigpy/ZHA). Recommend that you get the [Home Assistant SkyConnect / Home Assistant Connect ZBT-1 USB dongle](https://www.home-assistant.io/connectzbt1) as it is best supported and you indirectly sponsor the development of Home Assistant):

https://community.home-assistant.io/t/zigbee-buyers-guide/654695/2

 FYI, it is really easy to migrate to a new radio in ZHA if you buy a other adapter (and you do not even need to re-pair devices):

* https://www.home-assistant.io/integrations/zha#migrating-to-a-new-zigbee-coordinator-adapter-inside-zha

You can otherwise address the lack of support for ConBee in ZHA directly to Dresden Elektronik (who makes ConBee/RaspBee radio adapters and the deconz firmware for them), as while deconz firmware that ConBee/RaspBee uses might already have support for install-code and qr-code provisioning or not, but in any case, Dresden Elektronik has not yet published any specific documentation for how to use it with their serial protocol that ZHA/zigpy and other third-party applications depends on so they can not use it. This has been requested for a long time but slow respons from Dresden Elektronik's deconz developers in this regard, see:

* https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20
 
 and

* https://github.com/zigpy/zigpy-deconz/issues/214

**Closed as completed** 2024-08-15 19:21 UTC
