### ISSUE TITLE
[Device Support Request]  TS0021  _TZ3210_3ulg9kpo  New Tuya ZigBee 2 Gang 6 Scene Switch Push Button Controller

### ISSUE THREAD

**Issue by tiket84** [zigpy/zha-device-handlers#3007] opened 2024-02-26 20:33 UTC
### Problem description

Hello, I have bought a tuya Tuya ZigBee 2 Gang 6 Scene Switch Push Button Controller but it doesn't work in ZHA. Could you add the device or publish a quirk?
![TS0021 _TZ3210_3ulg9kpo](https://github.com/zigpy/zha-device-handlers/assets/142236534/4bca7709-3318-4c07-bb45-1eb42ade23c7)

### Solution description

add the device in ZHA

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by NdK73** [comment] 2024-03-17 07:37
Duplicate of #2847 .

**Closed as completed** 2024-08-11 17:44 UTC
Labels: Tuya
