### ISSUE TITLE
_TZE204_ntcy3xu1 Smoke detector, battery missing

### ISSUE THREAD

**Issue by erkr** [zigpy/zha-device-handlers#3589] opened 2024-12-07 15:40 UTC
### Bug description

Hi, I own a Tuya smoke detector.  With the `released quirk`, only the smoke sensor is exposed, but the battery entity is missing.
for Model _TZE204_ntcy3xu1. 
I have a custom quirk (see below), that offers the battery sensor, but the value readout is not correct. It jumps from 100% immediately to 5%

### Steps to reproduce

Na

### Expected behavior

Please Include the battery entity as well. 

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": {
    "logical_type": 2,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 128,
    "manufacturer_code": 4417,
    "maximum_buffer_size": 66,
    "maximum_incoming_transfer_size": 66,
    "server_mask": 10752,
    "maximum_outgoing_transfer_size": 66,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0004",
        "0x0005",
        "0x000f",
        "0x0500",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE204_ntcy3xu1",
  "model": "TS0601",
  "class": "TS0601_TZE204_ntcy3xu1.TuyaSmokeDetector0601"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Additional information

<details><summary>Custom quirk</summary>

```python

import logging

import zigpy.profiles.zha
from zigpy.quirks import CustomDevice
import zigpy.types as t
from zigpy.zcl.clusters.general import (
    Basic,
    Groups,
    Ota,
    Scenes,
    Time,
    BinaryInput,
    BatterySize,
)
from zigpy.zcl.clusters.security import IasZone
from zhaquirks import Bus
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
    ZONE_TYPE,
)
from zhaquirks.tuya import (
    TuyaLocalCluster,
    TuyaManufCluster,
    TuyaManufClusterAttributes,
    TuyaPowerConfigurationCluster,
)

_LOGGER = logging.getLogger(__name__)

TUYA_SMOKE_DETECTED_ATTR = 0x0401  # [0]/[1] [Detected]/[Clear]!
TUYA_SMOKE_TAMPERED_ATTR = 0x0104  # [0]/[1] [Clear]/[Tampered]!
TUYA_SMOKE_BATTERY_ATTR = 0x040e  # [0]/[1]/[2] [Low]/[Med]]/[Full]!


class TuyaSmokeDetectorCluster(TuyaManufClusterAttributes):
    """Manufacturer Specific Cluster of the TS0601 smoke detector."""

    attributes = {
        TUYA_SMOKE_DETECTED_ATTR: ("smoke_detected", t.uint8_t, True),
        TUYA_SMOKE_TAMPERED_ATTR: ("tampered_device", t.uint8_t, True),
        TUYA_SMOKE_BATTERY_ATTR: ("battery_status", t.uint8_t, True),
    }

    def _update_attribute(self, attrid, value):
        super()._update_attribute(attrid, value)
        if attrid == TUYA_SMOKE_DETECTED_ATTR:
            status = IasZone.ZoneStatus.Alarm_1 if value == 0 else 0
            self.endpoint.device.ias_bus.listener_event("update_attribute", "zone_status", status)
        elif attrid == TUYA_SMOKE_TAMPERED_ATTR:
            self.endpoint.device.tamper_detection_bus.listener_event(
                "update_attribute", "present_value", bool(value)
            )
        elif attrid == TUYA_SMOKE_BATTERY_ATTR:
            batt = 5 if value == 0 else 40 if value == 1 else 100
            self.endpoint.device.battery_bus.listener_event("battery_change", batt)
        else:
            _LOGGER.warning(
                "[0x%04x:%s:0x%04x] unhandled attribute: 0x%04x",
                self.endpoint.device.nwk,
                self.endpoint.endpoint_id,
                self.cluster_id,
                attrid,
            )


class TuyaIasZone(TuyaLocalCluster, IasZone):
    """
    IAS Zone: this generates the "Smoke" entity for HA.
    Receives updates from TuyaSmokeDetectorCluster.
    """

    _CONSTANT_ATTRIBUTES = {ZONE_TYPE: IasZone.ZoneType.Fire_Sensor}

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.ias_bus.add_listener(self)


class TuyaPowerConfigCluster(TuyaPowerConfigurationCluster):
    """
    Power Config Cluster: this generates the "Battery" entity for HA.
    Receives updates from TuyaSmokeDetectorCluster.
    """

    _CONSTANT_ATTRIBUTES = {
        TuyaPowerConfigurationCluster.attributes_by_name["battery_size"].id: BatterySize.AAA,
        TuyaPowerConfigurationCluster.attributes_by_name["battery_quantity"].id: 2,
        TuyaPowerConfigurationCluster.attributes_by_name["battery_rated_voltage"].id: 15,
    }


class TuyaTamperDetection(TuyaLocalCluster, BinaryInput):
    """
    Tamper Detection Cluster: this generates the "Binary input" entity for HA, which is updated
    with the Tampered state. Receives updates from TuyaSmokeDetectorCluster.
    """

    _CONSTANT_ATTRIBUTES = {
        BinaryInput.attributes_by_name["description"].id: "Tamper Detected",
        BinaryInput.attributes_by_name["active_text"].id: "Tampered",
        BinaryInput.attributes_by_name["inactive_text"].id: "Clear",
    }

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.tamper_detection_bus.add_listener(self)


class TuyaSmokeDetector0601(CustomDevice):
    """TS0601 Smoke detector quirk."""

    def __init__(self, *args, **kwargs):
        """Init."""
        self.ias_bus = Bus()
        self.battery_bus = Bus()
        self.tamper_detection_bus = Bus()
        super().__init__(*args, **kwargs)

    signature = {
        MODELS_INFO: [
            ("_TZE204_ntcy3xu1", "TS0601"),
        ],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zigpy.profiles.zha.PROFILE_ID,
                DEVICE_TYPE: zigpy.profiles.zha.DeviceType.SMART_PLUG,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaManufCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Time.cluster_id,
                    Ota.cluster_id,
                ],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zigpy.profiles.zha.PROFILE_ID,
                DEVICE_TYPE: zigpy.profiles.zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaIasZone,
                    TuyaSmokeDetectorCluster,
                    TuyaPowerConfigCluster,
                    TuyaTamperDetection,
                ],
                OUTPUT_CLUSTERS: [
                    Time.cluster_id,
                    Ota.cluster_id,
                ],
            },
        },
    }
```

</details>

**Comment by prairiesnpr** [comment] 2024-12-08 11:07
That looks like expected behavior, DP 14 is a boolean that indicates if the battery is low according to the corresponding z2m converter.

**Comment by erkr** [comment] 2024-12-08 11:41
> That looks like expected behavior, DP 14 is a boolean that indicates if the battery is low according to the corresponding z2m converter.

Thanks. Then the 
Custom Quirk implementation will be right. How to get it added to the official quirk for this device?

**Comment by prairiesnpr** [comment] 2024-12-08 12:24
Does this quirk work? Need to be on HA 2024.11 or newer.

```python
from zhaquirks.tuya import TuyaLocalCluster
from zigpy.zcl.clusters.security import IasZone

from zhaquirks.tuya.builder import TuyaPowerConfigurationCluster2AAA, TuyaQuirkBuilder

class TuyaIAS(IasZone, TuyaLocalCluster):
    """Tuya local IAS cluster."""

    _CONSTANT_ATTRIBUTES = {
        IasZone.AttributeDefs.zone_type.id: IasZone.ZoneType.Fire_Sensor
    }

(
    TuyaQuirkBuilder("_TZE204_ntcy3xu1", "TS0601")
    .tuya_dp(
        dp_id=1,
        ep_attribute=TuyaIAS.ep_attribute,
        attribute_name=IasZone.AttributeDefs.zone_status.name,
        converter=lambda x: IasZone.ZoneStatus.Alarm_1 if x == 1 else 0,
    )
    .adds(TuyaIAS)
    .tuya_dp(
        dp_id=14,
        ep_attribute=TuyaPowerConfigurationCluster2AAA.ep_attribute,
        attribute_name="battery_percentage_remaining",
        converter=lambda x: {0: 5, 1: 40, 2: 100}[x],
    )
    .adds(TuyaPowerConfigurationCluster2AAA)
    .skip_configuration()
    .add_to_registry()
)
```

**Comment by erkr** [comment] 2024-12-08 13:26
@prairiesnpr   Yes that works!!! Wauw
Please get this in the release 😀

Update: performing some extra testing and report on that later (replaced the batteries and waiting for the first update)

**Comment by erkr** [comment] 2024-12-08 14:22
@prairiesnpr 
Some extra testing is good. The V2 quirk creates the right entities, but those don't seem to work (still have to verify the battery)

Note that Tamper doesn't work in both quirks. That one probably could be left out. But smoke detect doesn't work in V2 (works fine in the V1)

**Comment by prairiesnpr** [comment] 2024-12-08 14:25
Can you grab logs on what value is being returned when it detects smoke and when cleared?

**Comment by erkr** [comment] 2024-12-08 14:26
Yes, but some guidance please. Should I enable the debug log for Zha component?

**Comment by erkr** [comment] 2024-12-08 14:29
The battery implementation seems different in the V2 version, so that needs to be tested as well
V1 reports 5 for 0 and 40 for 1 (never seen that value) and 100 for other values (full batteries do report 100)
So I guess, if you are right that it is a bool, TRUE isn't 1, but something like 0xFF

**Comment by prairiesnpr** [comment] 2024-12-08 14:31
Yes, enable debug logging in ZHA, then if you can cut it to just the timestamps when are testing we should see the traffic and be able to tell where I went wrong.

**Comment by erkr** [comment] 2024-12-08 14:52
I logged with my old V1 quirk. Device info: 
```
IEEE: a4:c1:38:66:3a:ee:86:34
Nwk: 0xcd84
Device Type: EndDevice
LQI: 255
RSSI: -79
Last seen: 2024-12-08T15:42:20
Power source: Battery or Unknown
Quirk: TS0601_TZE204_ntcy3xu1.TuyaSmokeDetector0601
```
Look at timestamp 15:42:19.464

Thanks for your help!
[ZHA debug Smoke.txt](https://github.com/user-attachments/files/18052681/ZHA.debug.Smoke.txt)

**Comment by erkr** [comment] 2024-12-08 15:01
Don't know if it is relevant; I enabled the V2 quirk by reloading ZHA, not a full restart
For reverting to the V1, reload wasn't enough, so I did full restart for that

**Comment by prairiesnpr** [comment] 2024-12-08 19:18
> Don't know if it is relevant; I enabled the V2 quirk by reloading ZHA, not a full restart For reverting to the V1, reload wasn't enough, so I did full restart for that

Looked at logs, battery is an enum, and I had used zone_state instead of zone_status, please test the updated quirk above and let me know if that does it.

**Comment by prairiesnpr** [comment] 2024-12-08 19:42
> Note that Tamper doesn't work in both quirks. That one probably could be left out. But smoke detect doesn't work in V2 (works fine in the V1)

I didn't see any traffic in your logs related to the tamper sensor so going to remove it.

**Comment by erkr** [comment] 2024-12-08 20:27
Test it tomorrow 👌

**Comment by erkr** [comment] 2024-12-09 09:58
> Test it tomorrow 👌

Just tried the new version. It only offers the battery. Alarm sensor is gone.

PS: I didn't trigger tamper in the provided log. I will record one for tamper as well

**Comment by prairiesnpr** [comment] 2024-12-09 10:16
> > Test it tomorrow 👌
> 
> Just tried the new version. It only offers the battery. Alarm sensor is gone.
> 
> PS: I didn't trigger tamper in the provided log. I will record one for tamper as well

My bad, cp error, needed `.adds(TuyaIAS)`, added it above.

**Comment by erkr** [comment] 2024-12-09 10:54
@prairiesnpr 
Improved, the alarm sensor in present and triggers. But afterwards it doesn't clear!
I have a battery report from 100% to 50%. Wierd as the code makes it 40?!

**Comment by prairiesnpr** [comment] 2024-12-09 10:59
That's very odd, if you look at the PR, I actually have a test using the two packets from your logs above, the trigger and the following clear. Maybe worth trying a restart?

**Comment by erkr** [comment] 2024-12-09 11:17
I will try that!
I checked, there is noting logged when triggering tamper

**Comment by erkr** [comment] 2024-12-09 11:28
@prairiesnpr 
A restart doesn't fix it. I made a short debug log (device  0xcd84) while pressing the test button. When I press the button, it very briefly switches to clear, and back to detected, and then it stays like that. So I guess maybe the state is reverted!

[ZHA debug Smoke2.txt](https://github.com/user-attachments/files/18060744/ZHA.debug.Smoke2.txt)

Update: 
Yest that was it. Changed this line to make it work:
        `converter=lambda x: IasZone.ZoneStatus.Alarm_1 if x == 0 else 0,`
PS: leaving the whole line out, doesn't work

I see in the PR you changed two things at ounce (state to status, and changed the lambda):
```
      IasZone.AttributeDefs.zone_status.name,
      converter=lambda x: IasZone.ZoneStatus.Alarm_1 if x == 1 else 0,
```

Other note: All the testing seems to deplete the batteries quickly. Strange is that the battery reports 50% (instead of the coded 40% in the quirk). Doubth if this line is working (and maybe not needed): ` converter=lambda x: {0: 5, 1: 40, 2: 100}[x],`

**Comment by prairiesnpr** [comment] 2024-12-09 12:14
> Other note: All the testing seems to deplete the batteries quickly. Strange is that the battery reports 50% (instead of the coded 40% in the quirk). Doubth if this line is working (and maybe not needed): ` converter=lambda x: {0: 5, 1: 40, 2: 100}[x],`

Zigbee values are supposed to be doubled, I don't recall where the conversation takes place right now though. You can try `converter=lambda x: {0: 10, 1: 80, 2: 200}[x],`

I'm at work right now, will look at your logs this evening.

Good news on the inversion, I'll correct the PR tonight.

**Comment by erkr** [comment] 2024-12-09 12:25
> Zigbee values are supposed to be doubled, I don't recall where the conversation takes place right now though. You can try `converter=lambda x: {0: 10, 1: 80, 2: 200}[x],`

Changed the line and waiting for the next battery update...
I start to understand the logging :-) The raw battery value in the log is 0x02, so doubling seems right.

Update: with this 'doubling modification' it reports 100% for raw value 0x02. These relevant lines where in the log when pressing the test button:
```
[Alarm on]: 2024-12-09 13:46:41.068 DEBUG (MainThread) [zigpy.zcl] [0xCD84:1:0xef00] Received command 0x02 (TSN 105): set_data_response(data=TuyaCommand(status=0, tsn=55, datapoints=[TuyaDatapointData(dp=1, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x00', *payload=<enum8.undefined_0x00: 0>))]))
[battery]: 2024-12-09 13:46:41.215 DEBUG (MainThread) [zigpy.zcl] [0xCD84:1:0xef00] Received command 0x02 (TSN 106): set_data_response(data=TuyaCommand(status=0, tsn=56, datapoints=[TuyaDatapointData(dp=14, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x02', *payload=<enum8.undefined_0x02: 2>))]))
[Alarm off]: 2024-12-09 13:46:42.045 DEBUG (MainThread) [zigpy.zcl] [0xCD84:1:0xef00] Received command 0x02 (TSN 107): set_data_response(data=TuyaCommand(status=0, tsn=57, datapoints=[TuyaDatapointData(dp=1, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x01', *payload=<enum8.undefined_0x01: 1>))]))
```
Thanks for your help

**Comment by prairiesnpr** [comment] 2024-12-09 13:09
> Update: with this 'doubling modification' it reports 100% for raw value 0x02. These relevant lines where in the log when pressing the test button:

Perfect, PR is updated once it's merged you should be good.

**Comment by erkr** [comment] 2024-12-09 13:22
@prairiesnpr 
I'm not that familiar with reviewing commits, but looking at the latest battery update, the file ts0601_smoke contains this:
```
(
    TuyaQuirkBuilder("_TZE204_ntcy3xu1", "TS0601")
    .tuya_ias(dp_id=1)
    .tuya_dp(
        dp_id=14,
        ep_attribute=TuyaPowerConfigurationCluster2AAA.ep_attribute,
        attribute_name="battery_percentage_remaining",
        converter=lambda x: {0: 10, 1: 80, 2: 200}[x],
    )
    .adds(TuyaPowerConfigurationCluster2AAA)
    .skip_configuration()
    .add_to_registry()
)
```
Is the DP1 specialization not missing here?:
```
    .tuya_dp(
        dp_id=1,
        ep_attribute=TuyaIAS.ep_attribute,
        attribute_name=IasZone.AttributeDefs.zone_status.name,
        converter=lambda x: IasZone.ZoneStatus.Alarm_1 if x == 0 else 0,
    )
    .adds(TuyaIAS)
```
Or is that the default for:
```
    .tuya_ias(dp_id=1)
```

**Comment by prairiesnpr** [comment] 2024-12-09 13:32
> Or is that the default for:
> 
> ```
>     .tuya_ias(dp_id=1)
> ```

That's correct, see https://github.com/prairiesnpr/zha-device-handlers/blob/dee4296a65f49efee31231fd9807b5c3b67bb45b/zhaquirks/tuya/builder/__init__.py#L122

Since all of the smoke quirks used the same logic, I took the opportunity to add a helper method to TuyaQuirkBuilder and update all of the old style quirks in the same PR.

**Comment by erkr** [comment] 2024-12-09 13:35
Learning all the time, thanks, looks great. Looking forward to have it in the release
best Eric

**Comment by erkr** [comment] 2024-12-09 15:00
@prairiesnpr  Sorry, I have another small question. Since I played with this custom quirk, Reloading the ZHA integration gives this error: 
`zigpy.exceptions.MultipleQuirksMatchException: Multiple matches found for device <Device model='TS0601' manuf='_TZE204_ntcy3xu1'`
When I fully restart HA, ZHA loads normal, but reloading still will fail. Is there some cache I can cleanup ?!

Update: found the cause: https://github.com/zigpy/zigpy/issues/1508, This work around works:
```
...
from zigpy.quirks import DEVICE_REGISTRY
del DEVICE_REGISTRY._registry_v2[("_TZE204_ntcy3xu1", "TS0601")]

class TuyaIAS(IasZone, TuyaLocalCluster):
...
```
<details><summary><b>Final custom quirk</b> for TZE204_ntcy3xu1</summary>

```
from zhaquirks.tuya import TuyaLocalCluster
from zigpy.zcl.clusters.security import IasZone

from zhaquirks.tuya.builder import TuyaPowerConfigurationCluster2AAA, TuyaQuirkBuilder

from zigpy.quirks import DEVICE_REGISTRY
if DEVICE_REGISTRY._registry_v2[("_TZE204_ntcy3xu1", "TS0601")]:
    del DEVICE_REGISTRY._registry_v2[("_TZE204_ntcy3xu1", "TS0601")]


class TuyaIAS(IasZone, TuyaLocalCluster):
    """Tuya local IAS cluster."""

    _CONSTANT_ATTRIBUTES = {
        IasZone.AttributeDefs.zone_type.id: IasZone.ZoneType.Fire_Sensor
    }

(
    TuyaQuirkBuilder("_TZE204_ntcy3xu1", "TS0601")
    .tuya_dp(
        dp_id=1,
        ep_attribute=TuyaIAS.ep_attribute,
        attribute_name=IasZone.AttributeDefs.zone_status.name,
        converter=lambda x: IasZone.ZoneStatus.Alarm_1 if x == 0 else 0,
    )
    .adds(TuyaIAS)
    .tuya_dp(
        dp_id=14,
        ep_attribute=TuyaPowerConfigurationCluster2AAA.ep_attribute,
        attribute_name="battery_percentage_remaining",
        converter=lambda x: {0: 10, 1: 80, 2: 200}[x],
    )
    .adds(TuyaPowerConfigurationCluster2AAA)
    .skip_configuration()
    .add_to_registry()
)
```
</details>

Thanks again for all the help

Best Eric

**Closed as completed** 2024-12-09 22:54 UTC
