### ISSUE TITLE
[Device Support Request] Add TS0601 Illumination sensor variant in Tuya device handler file

### ISSUE THREAD

**Issue by ErikApption** [zigpy/zha-device-handlers#2018] opened 2022-12-18 05:37 UTC
**Is your feature request related to a problem? Please describe.**
Variant "_TZE200_khx7nnka" of the "TS0601" Illumination sensor is not recognized correctly and doesn't show any sensor.

**Describe the solution you'd like**
The [current device handler](https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_illuminance.py) needs to add support for a new variant of the Illumination Sensor 

Adding the device ID in the current quirk file resolves the issue and the Illumination shows up correctly in HomeAssistant

```python

class TuyaIlluminance(CustomDevice):
    """HOME-LUX illuminance sensor. Sense maximum 1000 lumen."""

    signature = {
        #  endpoint=1, profile=260, device_type=81, device_version=1,
        #  input_clusters=[4, 5, 61184, 0], output_clusters=[25, 10])
        MODELS_INFO: [
            ("_TZE200_yi4jtqq1", "TS0601"),
            ("_TZE200_khx7nnka", "TS0601"),            
        ],
        ENDPOINTS: {
```

**Comment by javicalle** [comment] 2022-12-18 12:29
Duplicate of #2014

**Closed by javicalle** 2022-12-18 12:29 UTC
