### ISSUE TITLE
[Device Support Request] Xiaomi Aqara D1 double key wireless wall switch WXKG07LM

### ISSUE THREAD

**Issue by WarMachine228** [zigpy/zha-device-handlers#394] opened 2020-06-30 17:30 UTC
Please provide support for the enw wireless switch.  It can pair but there is no quirk.
Z2m page: [here](https://www.zigbee2mqtt.io/devices/WXKG07LM.html)
Thanks

**Comment by Adminiuga** [comment] 2020-06-30 19:54
Do you get any zha_event ? 
Can you provide information requested in the issue template?

**Comment by Adminiuga** [comment] 2020-06-30 19:55
Per se having a quirk is a not strict requirement for device to work with ZHA

**Comment by WarMachine228** [comment] 2020-07-01 06:02
No zha event.
No triggers when creating automation in gui.
![image](https://user-images.githubusercontent.com/48219479/86208561-5fd3c980-bba3-11ea-900f-9dcf4c34c6a0.png)
I
 will post the log file later

**Comment by WarMachine228** [comment] 2020-07-01 08:36
This is the log of the pairing
[zha.txt](https://github.com/zigpy/zha-device-handlers/files/4856672/zha.txt)

**Comment by dmulcahey** [comment] 2020-07-05 23:17
Have one coming on the slow boat... will see what’s up when I get it.

**Comment by egelmex** [comment] 2020-08-06 17:28
I have just tried to pair a d1 three way switch, 

`{
  "node_descriptor": "<Optional byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=4447 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=11264 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0702",
        "0x0b04"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": []
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.switch.n3acn3",
  "class": "zigpy.device.Device"
}`

**Comment by sshaikh** [comment] 2020-09-09 16:50
I have a similar request re QBKG25LM aka lumi.switch.l3acn3. It's supported by z2m, so I presume it's a quirk issue. One button works, the others don't.

```
{
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4447 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=11264 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0012",
        "0xfcc0"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0012",
        "0xfcc0"
      ],
      "out_clusters": []
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0012",
        "0xfcc0"
      ],
      "out_clusters": []
    },
    "41": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "42": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "43": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "51": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "52": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "53": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0012"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.switch.l3acn3",
  "class": "zigpy.device.Device"
}
```

**Comment by Adminiuga** [comment] 2020-09-09 16:57
the problem is with `zigpy-cc`. If your stick is running ZStack 3.x, then switch to zigpy-znp in the new HA beta and it should take care of it.

**Comment by sshaikh** [comment] 2020-09-09 17:05
Thanks for the pointer. 

I'm using the usb stick as per https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html. So presume I'm running an old stack.

There are details here on the 3.0 stack: https://github.com/Koenkk/zigbee2mqtt/issues/1445

**Comment by sshaikh** [comment] 2020-09-09 18:16
@Adminiuga just to clarify, do I need zstack 3 to use this device at all, or to most easily use this device in HA natively?

I ask as it's unclear whether the cc2531 with v3 will work with zigpy-znp so I'm trying to figure out the best way to proceed.

**Comment by Adminiuga** [comment] 2020-09-09 18:37
CC2531 with ZStack 3.x would work with `zigpy-znp`

**Comment by sshaikh** [comment] 2020-09-10 15:52
Updating to ZStack 3, switching to beta and readding all my devices did the trick.

**Comment by dmulcahey** [comment] 2020-10-10 13:10
closing as these are supported

**Closed by dmulcahey** 2020-10-10 13:10 UTC
