### ISSUE TITLE
Howto Install zha-device-handlers

### ISSUE THREAD

**Issue by kevintedder** [zigpy/zha-device-handlers#1517] opened 2022-04-21 16:02 UTC
HELP.  I'm new to HA.
Having installed HA, ZHA & deCONZ on a RPI3B, I can pair with a TS0601 TRV device, but cannot read/write any info.
It appears that I need a device handlers in order to progress - hence I think I need this repo.  But how do I install it? The README talks about installing a development environment, but I'm planning on developing anything (yet). I just want to read this TS0601.

I have open a SSH terminal and cloned this repo onto my RPI3B, but when I run the script/setup it crashes with:

[core-ssh zha-device-handlers]$ ./script/setup
./script/setup: line 17: python3: command not found

[core-ssh zha-device-handlers]$ where python3
bash: where: command not found

[core-ssh zha-device-handlers]$ find / -name python3 -print
/usr/share/bash-completion/completions/python3

So python3 does exist.

What am I doing wrong?

**Comment by Hedda** [comment] 2022-04-25 12:00
If you followed standard Home Assistant installation then ZHA will use quirks only if there is a quirk available for your specific device, if there is not then you can search other issues if there is an existing custom ZHA device handler (custom quirk) available that has not yet been merged into previous releases of ZHA Device Handlers For Home Assistant. 

https://github.com/zigpy/zha-device-handlers/releases

https://github.com/zigpy/zha-device-handlers/pulls?q=is%3Apr+

https://github.com/zigpy/zha-device-handlers/issues?q=is%3Aissue

If one exists then you can add that quirk manually as a temporary workaround until merged, if not then you either need to request a new ZHA device handler (quirk) or make/edit your own (which is normally done by editing an existing quirk for a similar device).

https://www.home-assistant.io/integrations/zha#knowing-which-devices-are-supported

https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling

Not sure what your setup is to maybe can start by providing the information asked for in bug report and device request forms?

Especially the Device signature and the Diagnostic information is essential info needed for details on specific device you got.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

<details>
<summary>Device signature - this can be acquired by clicking on the "Zigbee Device Signature" button in the device settings</summary>

```
Paste the device signature here.
```

</details>

<details>
<summary>Diagnostic information - this can be acquired by clicking on the "Download Diagnostics" button in the device settings</summary>

```
Paste the diagnostic information here.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
```

</details>

**Additional context**
Add any other context about the problem here.



**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

<details>
<summary>Device signature - this can be acquired by clicking on the "Zigbee Device Signature" button in the device settings</summary>

```
Paste the device signature here.
```

</details>

<details>
<summary>Diagnostic information - this can be acquired by clicking on the "Download Diagnostics" button in the device settings</summary>

```
Paste the diagnostic information here.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
```

</details>

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by kevintedder** [comment] 2022-04-25 13:02
@Hedda   This is NOT a bug, it is a usability issue.

Does ZHA-DEVICE_HANDLER support the following device signature?   YES or NO?

====BEGIN====
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_lllliz3p",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
====END====


If YES, then how do I implement ZHA-DEVICE-HANDLER on my system?

**Comment by dmulcahey** [comment] 2022-04-25 13:22
Also, you cannot run ZHA and deconz concurrently with the same zigbee stick

**Comment by kevintedder** [comment] 2022-04-25 14:41
@dmulcahey Ok.  deconz was removed before I loaded ZHA.

But why does ZHA not recognise the TS0601 TRV I have. Once ZHA has auto discovered it, it is shown as OFFLINE with only 2 entities (basic-lqi & basic rssi) ? There are no entities for the temperature controls.

**Comment by dmulcahey** [comment] 2022-04-25 15:12
Because tuya is a mess. Submit a device support request and hopefully someone will get to it.

**Comment by kevintedder** [comment] 2022-04-25 16:19
@dmulcahey   Thx.
I've raised the request.  So until this repo is update I'll have to register them with via the TUYA integration for now?

I assume once the repo is updated to recognise this device, HA will notify me of a new release and it will be installed automatically.  Is this correct?

**Comment by MattWestb** [comment] 2022-04-25 16:23
If we is knowing wot device you i like getting supported and its already being supported but with different ID its possible adding it as local quirk and you can getting it up and running in some minutes.
https://github.com/zigpy/zha-device-handlers/issues/1530

**Comment by Hedda** [comment] 2022-04-25 18:23
> I've raised the request. So until this repo is update I'll have to register them with via the TUYA integration for now?

As already mentioned above, if and when someone makes a custom quirk for your specific device then you can either wait until it is merged and included in a release or you do not want to wait then can choose to add it manually via "custom_quirks_path":

https://www.home-assistant.io/integrations/zha#custom_quirks_path

> I assume once the repo is updated to recognise this device, HA will notify me of a new release and it will be installed automatically. Is this correct?

As it works now zha-device-handlers (zha-quirks) released are made on an irregular basis, though historically around once a month. Those releases are normally then bumped relatively soon in Home Assistant core for release via PR. You can track here:

https://github.com/home-assistant/core/pulls?q=is%3Apr+zha+AND+quirks

https://github.com/zigpy/zha-device-handlers/releases

PS: Remember that the ZHA integration and its zigpy and zha-device-handlers dependencies are made by volunteers as a hobby.

**Comment by Hedda** [comment] 2022-06-07 07:43
I think this issue https://github.com/zigpy/zha-device-handlers/issues/1517 can be closed as per title "Howto Install zha-device-handlers" and original question has been answered, or?

For reference, [kevintedder](https://github.com/kevintedder) also posted some related questions refering to ZHA docs -> https://github.com/home-assistant/home-assistant.io/issues/22505

I think best would be if such questions were asked in other communication channels meant for help/support from the community:

https://www.home-assistant.io/help/

GitHub repositories should primarily be used for constructive feature requests and report bugs after already tried to troubleshot it.

So instead ask in the community forum for help/support or Discord Chat Server for general Home Assistant discussions/questions:

https://community.home-assistant.io

and

https://discord.gg/c5DvZ4e

Also, general tip before asking for help/support in a community for an free and open-source project like this is to read/follow this:

http://www.catb.org/~esr/faqs/smart-questions.html

PS: Again, remember that both developers and other people trying to assistant ZHA and zigpy as volunteers doing this as a hobby.

**Comment by MattWestb** [comment] 2022-06-07 15:45
lMy favorite is zigpy wiki pages if some one is putting in good information for user and devs and it shall being linked from the main zigpy page.
Also linking issues, discussions and other information to wiki pages is great.

**Comment by Hedda** [comment] 2022-10-19 14:13
For installing custom ZHA quirks also see this discussion -> https://github.com/zigpy/zha-device-handlers/discussions/693

Btw, I wrote this initial troubleshooting guide for the official ZHA integration on how to add custom ZHA quirks locally that was rejected:

https://github.com/home-assistant/home-assistant.io/pull/23884

That initial guide did however not cover how to map/define storage volumes with Docker-Compose  f using Home Assistant core in a Docker container but there it should be noted that the existing ZHA integration documentation does mention Docker Compose under troubleshooting:

https://www.home-assistant.io/integrations/zha#cant-connect-to-usb-device-and-using-docker

https://www.home-assistant.io/integrations/zha#docker-compose

Anyway, here is a copy of my guide for beginners:

https://github.com/home-assistant/home-assistant.io/pull/23884

#### Manually add and use a not yet merged custom ZHA quirk

If you have bought a non-standard Zigbee device that is not yet supported by ZHA but someone have written a ZHA "quirk" module (ZHA Device Handler/Zigbee Converter) that not get been merged into a "[ZHA Device Handlers"](https://github.com/zigpy/zha-device-handlers)" library release then you can add that manually as a custom ZHA quirk to your Home Assistant instance, (using something like File Editor or Samba share add-ons in Home Assistant).

1. Get a copy of an existing custom ZHA quirk or code your own quirks. Tip is to search using Zigbee device signature https://github.com/zigpy/zha-device-handlers/issues?q=is%3Aissue+is%3Aopen
2. Create a directory/folder for your custom quirks (for example `/config/zha_quirks/`)
3. Copy or create a quirk file in this directory (called it for example “`devicemodelzyz_devicetypexyz.py`”). This file should contain the Python script for the quirk and its specific Zigbee device signature unique to it. 
4. Add configuration with the full path to the directory that now containing custom quirk module(s) that will override and take precedence over any built-in quirks matching any device that has the same Zigbee device signature. to Home Assistant's config.yaml
```
zha:
  custom_quirks_path: /config/zha_quirks/
```
5. Restart Home Assistant to make the quirk take effect.

**Closed** 2022-10-30 13:11 UTC
