### ISSUE TITLE
[Device Support Request] - Door sensor Zigbee Tuya

### ISSUE THREAD

**Issue by antoweb** [zigpy/zha-device-handlers#2038] opened 2022-12-28 10:54 UTC
**Is your feature request related to a problem? Please describe.**
Tuya Door sensor Zigbee are recognized by zha sonoff dongle but wont work
![image](https://user-images.githubusercontent.com/32364871/209801244-4a0a76f4-2b7e-402b-8037-852b12da0aaa.png)

**Describe the solution you'd like**
I want to use these devices

<details>

<summary>Device signature</summary>

```yaml
Paste the device signature here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>

<summary>Diagnostic information</summary>

[zha-c7d6588cfe70f37b240c21695e499f8b-_TZE200_pay2.txt](https://github.com/zigpy/zha-device-handlers/files/10313798/zha-c7d6588cfe70f37b240c21695e499f8b-_TZE200_pay2.txt)

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**

**Comment by javicalle** [comment] 2022-12-29 11:20
Duplicate of #1502

You can try with the quirk from:
https://github.com/zigpy/zha-device-handlers/issues/1502#issuecomment-1366969811

**Closed by javicalle** 2022-12-29 11:20 UTC
