### ISSUE TITLE
Support for Xiaomi Mijia Plug [Power Reading]

### ISSUE THREAD

**Issue by mim212** [zigpy/zha-device-handlers#405] opened 2020-07-11 03:18 UTC
I've recently migrated my system over to zha from deconz, which is much better minus the support for power (Watts) from Xiaomi Mijia Plugs which just come through as a switch entity only. 

![image](https://user-images.githubusercontent.com/30016201/87215312-de392400-c378-11ea-8ce0-94a54e29f542.png)

zigbee device signature below
```
{
  "node_descriptor": "<NodeDescriptor byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=4447 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x000a",
        "0x0010"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0009",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": [
        "0x0004",
        "0x000c"
      ]
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0053",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": [
        "0x000c"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug",
  "class": "zigpy.device.Device"
}
```

**Comment by dmulcahey** [comment] 2020-07-12 12:52
Duplicate of #397 Closing this one.

**Closed by dmulcahey** 2020-07-12 12:52 UTC
